baseURL = "https://andrewrea.co.uk/"
languageCode = "en-gb"
pygmentsCodeFences = true
theme= "reaandrew"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser.attribute]
      block = true

[Author]
  name = "Andy Rea"
  email = "email@andrewrea.co.uk"
  github = "reaandrew"
  twitter = "rea_andrew"
  reddit = "reaandrew"
  linkedin = "reaandrew"
  stackoverflow = "users/67959/rea-andrew"
  youtube = "UCPQcL92tkPkvTdhQZ8EydKQ" # or channel/channelname