# https://willschenk.com/articles/2018/automating_hugo_with_circleci/
version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:

      # install git
      - run: apk update && apk add git

      # checkout the repository
      - checkout

      - run: git submodule sync && git submodule update --init

      - run: 
          name: "Remove the folder from the index"
          command: |
            git rm -f $HUGO_BUILD_DIR > /dev/null 2>&1 || :

      - run: rm -rf .git/modules/$HUGO_BUILD_DIR

      - run: git submodule add -b master git@github.com:reaandrew/reaandrew.github.io.git $HUGO_BUILD_DIR

      # build with Hugo
      - run: HUGO_ENV=production hugo -t book -v -d $HUGO_BUILD_DIR

      # Set some variables to add to the commit message
      - run: git config --global user.email "email@andrewrea.co.uk" && git config --global user.name "CircleCI Bot"

      # Push the generated files back to github
      - run: cd $HUGO_BUILD_DIR && git add --all && git commit -m "rebuilding site `date`" && git push
