name: Hugo Build and Deploy

on:
  push:
    branches:
      - main  # replace this with your default branch name if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Git
        run: sudo apt-get update && sudo apt-get install -y git

      - name: Install Hugo
        run: |
          HUGO_VERSION="0.92.1"  # replace with the desired version
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
          sudo dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb

      - name: Update and Initialize Git Submodules
        run: git submodule sync && git submodule update --init

      - name: Build Hugo
        env:
          HUGO_BUILD_DIR: public
        run: HUGO_ENV=production hugo -t reaandrew -v -d $HUGO_BUILD_DIR

      - name: Deploy to GitHub Pages
        uses: actions/gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
